/*
 * File: app/view/MyWindow.js
 *
 * This file was generated by Sencha Architect version 3.0.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'Ext.form.Panel',
        'Ext.tab.Panel',
        'Ext.tab.Tab',
        'Ext.ux.form.TinyMceTextArea',
        'Ext.panel.Tool'
    ],

    autoShow: true,
    height: 396,
    width: 645,
    layout: 'fit',
    title: 'TinyMCE Test',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    layout: 'fit',
                    bodyPadding: 0,
                    header: false,
                    title: 'My Form',
                    items: [
                        {
                            xtype: 'tabpanel',
                            activeTab: 0,
                            deferredRender: false,
                            tabPosition: 'bottom',
                            items: [
                                {
                                    xtype: 'panel',
                                    layout: 'anchor',
                                    bodyPadding: 10,
                                    title: 'Editor with Auto-Hide Controls and vesion control plugin',
                                    items: [
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'First Name',
                                            name: 'firstName'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            fieldLabel: 'Last Name',
                                            name: 'lastName'
                                        },
                                        {
                                            xtype: 'tinymce',
                                            anchor: '100% -60',
                                            fieldLabel: 'Enter some info about yourself',
                                            labelAlign: 'top',
                                            name: 'aboutYourself',
                                            plugin_fullscreen: true,
                                            plugin_paste: true,
                                            plugin_ice: true,
                                            statusbar: true,
                                            showFormattingToolbar: true,
                                            browserSpellCheck: true,
                                            languages: 'true',
                                            defaultLanguage: 'true',
                                            hideToolbarOnBlur: true,
                                            formattingToolbar: 'undo redo | bold italic underline strikethrough superscript subscript | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    layout: 'fit',
                                    title: 'Editor with No Footer',
                                    items: [
                                        {
                                            xtype: 'tinymce',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            name: 'description',
                                            plugin_fullscreen: true,
                                            plugin_paste: true,
                                            statusbar: false,
                                            showFormattingToolbar: false,
                                            browserSpellCheck: true,
                                            languages: 'true',
                                            defaultLanguage: 'true',
                                            formattingToolbar: 'undo redo | bold italic underline strikethrough superscript subscript | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | removeformat'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    layout: 'fit',
                                    title: 'Editor with Custom Toolbar',
                                    items: [
                                        {
                                            xtype: 'tinymce',
                                            fieldLabel: 'Label',
                                            hideLabel: true,
                                            name: 'resume',
                                            plugin_fullscreen: true,
                                            plugin_paste: true,
                                            plugin_ice: false,
                                            statusbar: true,
                                            showFormattingToolbar: true,
                                            browserSpellCheck: true,
                                            languages: 'true',
                                            defaultLanguage: 'true',
                                            formattingToolbar: 'undo redo | bold italic underline | removeformat'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ],
            tools: [
                {
                    xtype: 'tool',
                    handler: function(event, toolEl, owner, tool) {
                        Ext.Msg.alert("Hello there!","Check your debug console for the output from the form");
                        console.log(tool.up('window').down('form').getValues());
                    },
                    type: 'save'
                }
            ]
        });

        me.callParent(arguments);
    }

});